stages:
  - compiling
  - assembling
  - packaging

run-npm:
  stage: compiling
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./src/js/Static/*
      - ./src/css/*

copy-files:
  stage: assembling
  script:
    - mkdir passwords
    - rsync -r --exclude="vue" --exclude="js" --exclude="scss" src/* passwords
    - rsync -r src/js/Static passwords/js/
  artifacts:
    paths:
      - ./passwords

run-tar:
  stage: packaging
  script:
    - tar -zcf passwords.tar.gz passwords
  artifacts:
    paths:
      - ./passwords.tar.gz
