stages:
  - compiling
  - assembling
  - packaging
  - publishing

NPM:
  stage: compiling
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./src/js/Static/*
      - ./src/css/*

Assemble:
  stage: assembling
  script:
    - mkdir passwords
    - rsync -r --exclude="vue" --exclude="js" --exclude="scss" src/* passwords
    - rsync -r src/js/Static passwords/js/
  artifacts:
    paths:
      - ./passwords

Pack:
  stage: packaging
  script:
    - tar -zcf passwords.tar.gz passwords
    - echo "export JOB_ID=\"${CI_JOB_ID}\"" > job.id
  artifacts:
    paths:
      - ./passwords.tar.gz
      - job.id

Publish:
  stage: publishing
  script:
    - source job.id
    - echo "-----BEGIN PRIVATE KEY-----" > sign.key
    - echo $SIGN_KEY | tr " " "\n" >> sign.key
    - echo "-----END PRIVATE KEY-----" >> sign.key
    - SIGNATURE=$(openssl dgst -sha512 -sign ./sign.key ./passwords.tar.gz | openssl base64)
    - rm sign.key
    - 'curl -X POST -u "${API_USER}:${API_TOKEN}" ${API_URL} -H "Content-Type: application/json" -d "{\"download\":\"${CI_PROJECT_URL}-/jobs/${JOB_ID}/artifacts/file/passwords.tar.gz\",\"signature\":\"${SIGNATURE}\",\"nightly\":true}"'
  only:
    - master