stages:
  - build
  - pack

compile:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./src/js/Static/*
      - ./src/css/*

assemble:
  stage: pack
  script:
    - mkdir passwords
    - rsync -r --exclude="vue" --exclude="js" --exclude="scss" src/* passwords
    - rsync -r src/js/Static passwords/js/

zip:
  stage: pack
  script:
    - tar -zcf passwords.tar.gz passwords
  artifacts:
    paths:
      - ./passwords.tar.gz
