version: '2'

services:
  mysql:
    image: mariadb
    container_name: "passwords-mysql"
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: ./docker/php/
    container_name: "passwords-php"
    restart: on-failure
    links:
      - mysql
    volumes:
      - /var/www/html
      - ./src/:/var/www/html/custom_apps/passwords
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql:3306
#      - SQLITE_DATABASE
#      - POSTGRES_DB=nextcloud
#      - POSTGRES_USER=nextcloud
#      - POSTGRES_PASSWORD=nextcloud
#      - POSTGRES_HOST=postgres5432

  web:
    build: ./docker/nginx/
    container_name: "passwords-nginx"
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes_from:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "passwords-phpmyadmin"
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "nextcloud"
      PMA_ABSOLUTE_URI: http://localhost:8080
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: nextcloud

#  postgres:
#    image: postgres:alpine
#    container_name: "passwords-postgres"
#    restart: on-failure
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=nextcloud
#      - POSTGRES_USER=nextcloud
#      - POSTGRES_DB=nextcloud

#  iconserver:
#    image: matthiasluedtke/iconserver
#    container_name: "passwords-iconserver"
#    ports:
#      - 7070:7070
#    environment:
#      PORT: 7070

volumes:
  mysql:
  postgres: