version: '2'

services:
  db:
    image: mariadb
    container_name: "passwords-db"
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: ./docker/php/
    container_name: "passwords-php"
    restart: on-failure
    links:
      - db
    volumes:
      - /var/www/html
      - ./src/:/var/www/html/custom_apps/passwords

  web:
    image: nginx:alpine
    container_name: "passwords-nginx"
    restart: on-failure
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "passwords-phpmyadmin"
    ports:
      - 8080:80
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: "nextcloud"
      PMA_ABSOLUTE_URI: http://localhost:8080
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: nextcloud

volumes:
  db: