version: '2'

services:
  openldap:
    image: osixia/openldap
    container_name: "passwords-openldap"
    environment:
      LDAP_ORGANISATION: nextcloud
      LDAP_DOMAIN: nextcloud
      LDAP_ADMIN_PASSWORD: nextcloud

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: "passwords-phpldapadmin"
    ports:
      - 9090:443
    links:
      - openldap
    volumes:
    - ./docker/volumes/nginx:/container/service/phpldapadmin/assets/apache2/certs
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: default.pem
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: default.key

  app:
    links:
    - openldap