version: '2'

services:
  app:
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=postgres

  postgres:
    image: postgres:alpine
    container_name: "passwords-postgres"
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  pgadmin:
    image: dpage/pgadmin4
    container_name: "passwords-pgadmin"
    restart: on-failure
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nextcloud
      - PGADMIN_DEFAULT_PASSWORD=nextcloud

volumes:
  postgres: