version: '2'

services:
  app:
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_HOST=
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=postgres:5432

  postgres:
    image: postgres:alpine
    container_name: "passwords-postgres"
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud

  pgadmin:
    image: dpage/pgadmin4
    container_name: "passwords-pgadmin"
    restart: on-failure
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=nextcloud

volumes:
  postgres: